name: 🧪 Test

on:
  push:
    branches:
      - main
      - dev
      - v2
      - v2_rebased
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "contributors.yml"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "contributors.yml"
      - "**/*.md"

jobs:
  test:
    if: github.repository == 'remix-run/remix'
    uses: ./.github/workflows/reusable-test.yml
    with:
      node_version: '["latest"]'
